"use client";

import type { NavItem } from "@/lib/types";
import { sortNavSubItemsByLabel } from "@/lib/processos-form-order";
import {
  LayoutDashboard,
  Users,
  Calendar,
  FileText,
  Recycle,
  LogOut,
  Leaf,
  ChevronDown,
  Briefcase,
  FolderKanban,
  FileCheck,
  ShoppingCart,
  UserCog,
  Book,
  FileSignature,
  ClipboardPenLine,
  Landmark,
  Droplets,
  Trees,
  FolderClock,
  FolderCheck,
  PlusSquare,
  Building,
  Contact,
  ClipboardCheck,
  SearchCheck,
  Link as LinkIcon,
  BookText,
  ShieldCheck,
  Building2,
  ListTree,
  FileQuestion,
  BookMarked,
  Shield,
  BookOpenCheck,
  Mountain,
  Bird,
  NotebookText,
  BrainCircuit,
  HardHat,
  MessagesSquare,
  Waves,
  Share2,
  Users2,
  Globe,
  ClipboardList,
  Signal,
  Settings,
  Bell,
  History,
  Folder,
  Mail,
  Send,
  Truck,
  List,
  LineChart,
  BarChart2,
  Palette,
  FileArchive,
  Bot,
  DatabaseZap,
  Workflow,
  Scale,
  Sparkles,
  Map,
  MapPinned,
  Crosshair,
  FileSpreadsheet,
  BookOpen,
} from "lucide-react";

export const allNavItems: NavItem[] = [
  {
    href: "/",
    label: "Painel",
    icon: LayoutDashboard,
    roles: [
      "admin",
      "client",
      "cliente_autonomo",
      "representative",
      "technical",
      "sales",
      "financial",
      "gestor",
      "supervisor",
      "diretor_fauna",
      "advogado",
    ],
  },
  {
    label: "Financeiro",
    icon: Briefcase,
    roles: [
      "admin",
      "financial",
      "sales",
      "client",
      "representative",
    ],
    subItems: [
      {
        href: "/bank-access",
        label: "Acesso Bancário",
        icon: Landmark,
        roles: ["admin", "financial"],
      },
      {
        href: "/clients",
        label: "Clientes",
        icon: Users,
        roles: ["admin", "sales", "financial"],
      },
      {
        href: "/contracts",
        label: "Contratos",
        icon: FileSignature,
        roles: [
          "admin",
          "financial",
          "sales",
          "client",
          "representative",
        ],
      },
      {
        href: "/contracts-suppliers",
        label: "Contratos-Fornecedores",
        icon: FileSignature,
        roles: [
          "admin",
          "financial",
          "sales",
        ],
      },
      {
        href: "/financial/abc-curve",
        label: "Curva ABC",
        icon: LineChart,
        roles: ["admin", "financial"],
      },
      {
        href: "/financial/dre-contabil",
        label: "DRE Contábil",
        icon: BarChart2,
        roles: ["admin", "financial"],
      },
      {
        href: "/invoices",
        label: "Faturas",
        icon: FileText,
        roles: [
          "admin",
          "financial",
          "client",
          "representative",
        ],
      },
      {
        href: "/suppliers",
        label: "Fornecedores",
        icon: Truck,
        roles: ["admin", "financial"],
      },
      {
        href: "/cash-flow",
        label: "Lançamentos de Caixa",
        icon: Landmark,
        roles: ["admin", "financial"],
      },
      {
        href: "/external?url=https%3A%2F%2Fwww.nfse.gov.br%2FEmissorNacional%2FLogin%3FReturnUrl%3D%252fEmissorNacional&title=NFe-Eletr%C3%B4nica",
        label: "NFe-Eletrônica",
        icon: FileText,
        roles: ["admin", "financial"],
      },
      {
        href: "/proposals",
        label: "Orçamentos",
        icon: FileSpreadsheet,
        roles: [
          "admin",
          "financial",
          "sales",
          "client",
          "cliente_autonomo",
          "representative",
        ],
      },
      {
        href: "/commercial-proposals",
        label: "Propostas Comerciais",
        icon: ClipboardPenLine,
        roles: [
          "admin",
          "financial",
          "sales",
          "client",
          "representative",
        ],
      },
      {
        href: "/services",
        label: "Tabela de Serviços",
        icon: List,
        roles: ["admin", "financial"],
      },
    ],
  },
  {
    label: "Cadastro",
    icon: Book,
    roles: [
      "admin",
      "technical",
      "gestor",
      "diretor_fauna",
      "supervisor",
      "financial",
      "sales",
      "client",
      "cliente_autonomo",
      "representative",
      "advogado",
    ],
    subItems: [
      {
        href: "/empreendedores",
        label: "Empreendedores",
        icon: Contact,
        roles: [
          "admin",
          "technical",
          "gestor",
          "diretor_fauna",
          "supervisor",
          "financial",
          "sales",
          "client",
          "cliente_autonomo",
          "representative",
          "advogado",
        ],
      },
      {
        href: "/projects",
        label: "Empreendimentos",
        icon: Building,
        roles: [
          "admin",
          "technical",
          "gestor",
          "diretor_fauna",
          "supervisor",
          "financial",
          "sales",
          "client",
          "cliente_autonomo",
          "representative",
          "advogado",
        ],
      },
      {
        href: "/responsible-company",
        label: "Empresa Responsável",
        icon: Building2,
        roles: [
          "admin",
          "technical",
          "gestor",
          "diretor_fauna",
          "supervisor",
          "financial",
          "sales",
          "client",
          "cliente_autonomo",
          "representative",
          "advogado",
        ],
      },
    ],
  },
  {
    label: "Autorizações/Relatórios",
    icon: Recycle,
    roles: [
      "admin",
      "client",
      "cliente_autonomo",
      "representative",
      "technical",
      "gestor",
      "supervisor",
      "diretor_fauna",
      "advogado",
    ],
    subItems: [
      {
        href: "/car",
        label: "CAR",
        icon: FileText,
        roles: [
          "admin",
          "client",
      "cliente_autonomo",
          "representative",
          "gestor",
          "supervisor",
          "technical",
          "advogado",
        ],
      },
      {
        href: "/compliance",
        label: "Condicionantes",
        icon: ClipboardCheck,
        roles: [
          "admin",
          "client",
      "cliente_autonomo",
          "representative",
          "gestor",
          "supervisor",
          "technical",
          "advogado",
        ],
      },
      {
        href: "/intervencoes",
        label: "DAIA's",
        icon: Trees,
        roles: [
          "admin",
          "client",
      "cliente_autonomo",
          "representative",
          "gestor",
          "supervisor",
          "technical",
          "advogado",
        ],
      },
      {
        href: "/fauna",
        label: "Fauna",
        icon: Bird,
        roles: [
          "admin",
          "client",
      "cliente_autonomo",
          "representative",
          "technical",
          "gestor",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        href: "/licenses",
        label: "Licenças",
        icon: FileCheck,
        roles: [
          "admin",
          "client",
      "cliente_autonomo",
          "representative",
          "gestor",
          "supervisor",
          "technical",
          "advogado",
        ],
      },
      {
        label: "Monitoramento de Outorga",
        icon: BookMarked,
        roles: [
          "admin",
          "client",
      "cliente_autonomo",
          "representative",
          "gestor",
          "supervisor",
          "technical",
          "advogado",
        ],
        subItems: [
          {
            href: "/monitoring/manual",
            label: "Lançamento Manual",
            icon: ClipboardList,
            roles: [
              "admin",
              "client",
      "cliente_autonomo",
              "representative",
              "gestor",
              "supervisor",
              "technical",
              "advogado",
            ],
          },
          {
            href: "/monitoring/telemetric",
            label: "Telemetria (Real-time)",
            icon: Signal,
            roles: [
              "admin",
              "client",
      "cliente_autonomo",
              "representative",
              "gestor",
              "supervisor",
              "technical",
              "advogado",
            ],
          },
        ],
      },
      {
        href: "/outorgas",
        label: "Outorgas",
        icon: Droplets,
        roles: [
          "admin",
          "client",
      "cliente_autonomo",
          "representative",
          "gestor",
          "supervisor",
          "technical",
          "advogado",
        ],
      },
      {
        href: "/usos-insignificantes",
        label: "Usos Insignificantes",
        icon: Waves,
        roles: [
          "admin",
          "client",
      "cliente_autonomo",
          "representative",
          "gestor",
          "supervisor",
          "technical",
          "advogado",
        ],
      },
    ],
  },
  {
    href: "/autos-infracao-defesa",
    label: "Autos de Infração - Defesa",
    icon: Scale,
    roles: ["admin", "advogado"],
  },
  {
    label: "Vistoria em Campo",
    icon: SearchCheck,
    roles: [
      "admin",
      "technical",
      "gestor",
      "supervisor",
      "advogado",
      "client",
      "cliente_autonomo",
      "representative",
    ],
    subItems: [
      {
        href: "/inspections",
        label: "Consultar vistorias",
        icon: List,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        href: "/inspections/new",
        label: "Nova vistoria",
        icon: PlusSquare,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        href: "/inspections/reports",
        label: "Relatórios de Campo",
        icon: FileText,
        roles: [
          "admin",
          "client",
          "cliente_autonomo",
          "representative",
          "gestor",
          "supervisor",
          "technical",
          "advogado",
        ],
      },
    ],
  },
  {
    label: "Processos",
    icon: FolderKanban,
    roles: [
      "admin",
      "technical",
      "gestor",
      "supervisor",
      "advogado",
      "client",
      "representative",
    ],
    subItems: sortNavSubItemsByLabel([
      {
        href: "/requests",
        label: "Lista de processos",
        icon: List,
        roles: [
          "admin",
          "technical",
          "gestor",
          "supervisor",
          "advogado",
          "client",
          "representative",
        ],
      },
      {
        href: "/requests/new",
        label: "Novo processo",
        icon: PlusSquare,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
    ]),
  },
  {
    label: "AmbientaR IA",
    icon: Sparkles,
    roles: [
      "admin",
      "financial",
      "technical",
      "gestor",
      "supervisor",
      "diretor_fauna",
      "advogado",
    ],
    subItems: [
      {
        href: "/analise-ambiental",
        label: "Análise Geoespacial (IA)",
        icon: Globe,
        roles: [
          "admin",
          "technical",
          "gestor",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        href: "/studies/analise-socioambiental",
        label: "Análise socioambiental",
        icon: FileText,
        roles: [
          "admin",
          "technical",
          "gestor",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        label: "Assistente de IA",
        icon: BrainCircuit,
        roles: [
          "admin",
          "technical",
          "gestor",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
        subItems: [
          {
            href: "/studies/assistant?tipo=mira",
            label: "Águas / MIRA-IGAM",
            icon: Droplets,
            roles: [
              "admin",
              "technical",
              "gestor",
              "supervisor",
              "diretor_fauna",
              "advogado",
            ],
          },
          {
            href: "/studies/assistant?tipo=mcp",
            label: "Cruzamento de dados",
            icon: Workflow,
            roles: [
              "admin",
              "technical",
              "gestor",
              "supervisor",
              "diretor_fauna",
              "advogado",
            ],
          },
          {
            href: "/studies/assistant?tipo=financeiro",
            label: "Custos e contratos",
            icon: BarChart2,
            roles: ["admin", "technical", "gestor", "supervisor", "diretor_fauna", "advogado"],
          },
          {
            href: "/studies/assistant?tipo=geral",
            label: "Legislação e estudos",
            icon: BookOpenCheck,
            roles: [
              "admin",
              "technical",
              "gestor",
              "supervisor",
              "diretor_fauna",
              "advogado",
            ],
          },
          {
            href: "/studies/assistant?tipo=rag",
            label: "Síntese de texto",
            icon: FileArchive,
            roles: [
              "admin",
              "technical",
              "gestor",
              "supervisor",
              "diretor_fauna",
              "advogado",
            ],
          },
        ],
      },
      {
        href: "/reporting",
        label: "Relatórios de IA",
        icon: Recycle,
        roles: ["admin", "financial"],
      },
    ],
  },
  {
    label: "Elaboração de Estudos",
    icon: BookText,
    roles: [
      "admin",
      "technical",
      "gestor",
      "supervisor",
      "diretor_fauna",
      "advogado",
    ],
    subItems: [
      {
        href: "/studies/educacao-ambiental",
        label: "Educação Ambiental",
        icon: BookOpenCheck,
        roles: [
          "admin",
          "technical",
          "gestor",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        href: "/studies/eia-rima",
        label: "EIA/RIMA",
        icon: FileQuestion,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        href: "/studies/cavidades",
        label: "Estudo de Cavidades",
        icon: Mountain,
        roles: [
          "admin",
          "technical",
          "gestor",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        href: "/studies/fauna",
        label: "Estudos de Fauna",
        icon: Bird,
        roles: [
          "admin",
          "technical",
          "gestor",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        href: "/studies/ide-sisemanet",
        label: "IDE-SisemaNet",
        icon: MapPinned,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        href: "/studies/inventario",
        label: "Inventário Florestal",
        icon: ListTree,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        href: "/studies/las-ras",
        label: "LAS-RAS",
        icon: FileSignature,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        href: "/studies/mapas",
        label: "Mapas",
        icon: Map,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        href: "/studies/outorgas",
        label: "Outorgas",
        icon: Droplets,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        href: "/studies/pca",
        label: "PCA",
        icon: BookMarked,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        href: "/studies/pia",
        label: "PIA",
        icon: FileCheck,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        href: "/studies/prada",
        label: "PRADA",
        icon: Leaf,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        href: "/studies/barragem",
        label: "Projeto Técnico de Barragem",
        icon: Building2,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        href: "/studies/ptrf",
        label: "PTRF",
        icon: Trees,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        href: "/studies/rca",
        label: "RCA",
        icon: NotebookText,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        href: "/studies/relatorios-diversos",
        label: "Relatórios Diversos",
        icon: FileArchive,
        roles: [
          "admin",
          "technical",
          "gestor",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        href: "/studies/reserva-legal",
        label: "Reserva Legal",
        icon: ShieldCheck,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        href: "/studies/seguranca-barragens",
        label: "Segurança de Barragens",
        icon: Shield,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
    ],
  },
  {
    label: "Georeferenciamento",
    icon: Crosshair,
    roles: [
      "admin",
      "gestor",
      "supervisor",
      "diretor_fauna",
      "advogado",
    ],
    subItems: [
      {
        href: "/georeferenciamento",
        label: "Painel",
        icon: LayoutDashboard,
        roles: ["admin", "gestor", "supervisor", "diretor_fauna", "advogado"],
      },
      {
        href: "/georeferenciamento/processos",
        label: "Processos",
        icon: ClipboardList,
        roles: ["admin", "gestor", "supervisor", "diretor_fauna", "advogado"],
      },
      {
        href: "/georeferenciamento/rural",
        label: "Rural (SIGEF/INCRA)",
        icon: Trees,
        roles: ["admin", "gestor", "supervisor", "diretor_fauna", "advogado"],
      },
      {
        href: "/georeferenciamento/urbano",
        label: "Urbano (cartório)",
        icon: Building2,
        roles: ["admin", "gestor", "supervisor", "diretor_fauna", "advogado"],
      },
      {
        href: "/georeferenciamento/ambiental",
        label: "CAR / SICAR",
        icon: Leaf,
        roles: ["admin", "gestor", "supervisor", "diretor_fauna", "advogado"],
      },
      {
        href: "/georeferenciamento/campo",
        label: "Campo e levantamento",
        icon: Crosshair,
        roles: ["admin", "gestor", "supervisor", "diretor_fauna", "advogado"],
      },
      {
        href: "/georeferenciamento/documentos",
        label: "Documentação técnica",
        icon: FileSpreadsheet,
        roles: ["admin", "gestor", "supervisor", "diretor_fauna", "advogado"],
      },
      {
        href: "/georeferenciamento/validacoes",
        label: "Validações",
        icon: Scale,
        roles: ["admin", "gestor", "supervisor", "diretor_fauna", "advogado"],
      },
      {
        href: "/georeferenciamento/registro",
        label: "Cartório e registro",
        icon: BookOpen,
        roles: ["admin", "gestor", "supervisor", "diretor_fauna", "advogado"],
      },
      {
        href: "/georeferenciamento/referencias",
        label: "Referências normativas",
        icon: BookOpenCheck,
        roles: ["admin", "gestor", "supervisor", "diretor_fauna", "advogado"],
      },
    ],
  },
  {
    label: "Vendas & CRM",
    icon: ShoppingCart,
    roles: ["admin", "sales", "supervisor", "financial"],
    subItems: [
      {
        href: "/crm/alerts",
        label: "Alertas & Notificações",
        icon: Bell,
        roles: ["admin", "sales", "supervisor", "financial"],
      },
      {
        href: "/crm/settings",
        label: "Configurações CRM",
        icon: Settings,
        roles: ["admin", "sales", "supervisor", "financial"],
      },
      {
        href: "/crm/team",
        label: "Equipe & Desempenho",
        icon: Users,
        roles: ["admin", "sales", "supervisor", "financial"],
      },
      {
        href: "/crm/clients",
        label: "Gestão de Clientes",
        icon: Users,
        roles: ["admin", "sales", "supervisor", "financial"],
      },
      {
        href: "/social-media",
        label: "Mídias Sociais",
        icon: Share2,
        roles: ["admin", "sales", "supervisor", "financial"],
      },
      {
        href: "/crm/opportunities",
        label: "Oportunidades & Pipeline",
        icon: FolderKanban,
        roles: ["admin", "sales", "supervisor", "financial"],
      },
      {
        href: "/crm",
        label: "Painel de Vendas",
        icon: LayoutDashboard,
        roles: ["admin", "sales", "supervisor", "financial"],
      },
      {
        href: "/crm/reports",
        label: "Relatórios & Análises",
        icon: BarChart2,
        roles: ["admin", "sales", "supervisor", "financial"],
      },
      {
        href: "/crm/proposals",
        label: "Vendas & Propostas",
        icon: FileText,
        roles: ["admin", "sales", "supervisor", "financial"],
      },
    ],
  },
  {
    href: "/external?url=https%3A%2F%2Fconsultoriapimenta.com.br%3A2096%2F&title=Webmail",
    label: "Webmail",
    icon: Send,
    roles: [
      "admin",
      "technical",
      "sales",
      "financial",
      "gestor",
      "supervisor",
      "diretor_fauna",
      "advogado",
    ],
  },
  {
    href: "/oficios",
    label: "Ofícios e Comunicações",
    icon: Send,
    roles: [
      "admin",
      "client",
      "cliente_autonomo",
      "technical",
      "sales",
      "financial",
      "gestor",
      "supervisor",
      "diretor_fauna",
      "advogado",
    ],
  },
  {
    label: "Acessos Governamentais",
    icon: LinkIcon,
    roles: [
      "admin",
      "technical",
      "gestor",
      "financial",
      "sales",
      "supervisor",
      "diretor_fauna",
      "advogado",
    ],
    subItems: [
      {
        href: "/external?url=https%3A%2F%2Fsistemas.meioambiente.mg.gov.br%2Fconsulta-intervencao%2Fsite%2Flistar-decisoes&title=Consulta%20Interven%C3%A7%C3%A3o%20Ambiental",
        label: "Consulta Intervenção Ambiental",
        icon: BookText,
        roles: [
          "admin",
          "technical",
          "gestor",
          "financial",
          "sales",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        href: "/external?url=https%3A%2F%2Fsistemas.meioambiente.mg.gov.br%2Flicenciamento%2Fsite%2Fconsulta-licenca&title=Consulta%20de%20Licen%C3%A7as",
        label: "Consulta Licenciamento",
        icon: BookText,
        roles: [
          "admin",
          "technical",
          "gestor",
          "financial",
          "sales",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        href: "/external?url=https%3A%2F%2Fsistemas.meioambiente.mg.gov.br%2Flicenciamento%2Fsite%2Flista-outorgas&title=Consulta%20de%20Outorgas",
        label: "Consulta Outorgas",
        icon: BookText,
        roles: [
          "admin",
          "technical",
          "gestor",
          "financial",
          "sales",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        href: "/external?url=https%3A%2F%2Fservicos.ibama.gov.br%2Fctf%2F&title=CTF%2FIBAMA&newTab=true",
        label: "CTF/IBAMA",
        icon: LinkIcon,
        roles: [
          "admin",
          "technical",
          "gestor",
          "financial",
          "sales",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        href: "/external?url=https%3A%2F%2Fvisualizador.idesisema.meioambiente.mg.gov.br%2F&title=IDE-SisemaNet-MG",
        label: "IDE-SisemaNet-MG",
        icon: Globe,
        roles: ["admin", "technical", "gestor", "supervisor", "diretor_fauna", "advogado"],
      },
      {
        href: "/external?url=https%3A%2F%2Fwww.ibama.gov.br%2Fsei&title=SEI-IBAMA&newTab=true",
        label: "SEI-IBAMA",
        icon: LinkIcon,
        roles: [
          "admin",
          "technical",
          "gestor",
          "financial",
          "sales",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        href: "/external?url=https%3A%2F%2Fwww.sei.mg.gov.br%2Fsei%2Fcontrolador_externo.php%3Facao%3Dusuario_externo_logar%26id_orgao_acesso_externo%3D0&title=SEI-MG&newTab=true",
        label: "SEI-MG",
        icon: LinkIcon,
        roles: [
          "admin",
          "technical",
          "gestor",
          "financial",
          "sales",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        href: "/external?url=https%3A%2F%2Fecosistemas.meioambiente.mg.gov.br%2Fportalseguranca%2Flogin&title=SLA-Ecossistemas-MG&newTab=true",
        label: "SLA-Ecossistemas/MG",
        icon: LinkIcon,
        roles: [
          "admin",
          "technical",
          "gestor",
          "financial",
          "sales",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
    ],
  },
  {
    label: "Configurações",
    icon: Settings,
    roles: [
      "admin",
      "client",
      "cliente_autonomo",
      "representative",
      "technical",
      "sales",
      "financial",
      "gestor",
      "supervisor",
      "diretor_fauna",
      "advogado",
    ],
    subItems: [
      {
        href: "/ai-lab/automations",
        label: "Automações IA",
        icon: Bot,
        roles: ["admin"],
      },
      {
        href: "/settings/deleted-backups",
        label: "Backup de Dados Apagados",
        icon: History,
        roles: ["admin", "supervisor"],
      },
      {
        href: "/ai-lab/rag",
        label: "Base de Conhecimento (RAG)",
        icon: DatabaseZap,
        roles: ["admin"],
      },
      {
        href: "/settings/files",
        label: "Explorador de Arquivos",
        icon: Folder,
        roles: ["admin"],
      },
      {
        href: "/ai-lab",
        label: "Hub IA + MCP + RAG",
        icon: Bot,
        roles: ["admin"],
      },
      {
        href: "/settings#identidade-visual",
        label: "Identidade Visual",
        icon: Palette,
        roles: ["admin"],
      },
      {
        href: "/settings/company",
        label: "Informações da Empresa",
        icon: Building,
        roles: ["admin"],
      },
      {
        href: "/audit-log",
        label: "Log de Auditoria",
        icon: History,
        roles: ["admin", "supervisor"],
      },
      {
        href: "/ai-lab/mcp",
        label: "MCP & Ferramentas IA",
        icon: Workflow,
        roles: ["admin"],
      },
      {
        href: "/settings/ai-local-source",
        label: "Pasta Base IA (Local)",
        icon: Folder,
        roles: ["admin"],
      },
      {
        href: "/technical-responsible",
        label: "Responsáveis Técnicos",
        icon: HardHat,
        roles: ["admin", "supervisor", "gestor"],
      },
      {
        href: "/settings/appearance",
        label: "Aparência",
        icon: Palette,
        roles: [
          "admin",
          "client",
          "cliente_autonomo",
          "representative",
          "technical",
          "sales",
          "financial",
          "gestor",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        href: "/settings/templates",
        label: "Templates",
        icon: FileText,
        roles: ["admin"],
      },
      {
        href: "/users",
        label: "Usuários",
        icon: UserCog,
        roles: [
          "admin",
          "client",
          "cliente_autonomo",
          "representative",
          "sales",
          "supervisor",
          "technical",
          "gestor",
          "diretor_fauna",
          "financial",
          "advogado",
        ],
      },
    ],
  },
  {
    href: "/calendar",
    label: "Agenda",
    icon: Calendar,
    roles: [
      "admin",
      "technical",
      "financial",
      "gestor",
      "client",
      "cliente_autonomo",
      "representative",
      "supervisor",
      "sales",
      "diretor_fauna",
      "advogado",
    ],
  },
];
