"use client";

import type { NavItem } from "@/lib/types";
import {
  GEOREF_TRAMITES_SUBMENU_LABEL,
  LICENCIAMENTO_LIST_SUBITEM_LABEL,
  LICENCIAMENTO_MENU_LABEL,
  LICENCIAMENTO_NEW_SUBITEM_LABEL,
} from "@/lib/licenciamento-menu";
import {
  MULTAS_DEFESAS_LIST_LABEL,
  MULTAS_DEFESAS_NOVA_LABEL,
  MULTAS_DEFESAS_NOVA_PATH,
  MULTAS_DEFESAS_PATH,
  MULTAS_E_DEFESAS_MENU_LABEL,
} from "@/lib/multas-defesas-menu";
import { OFICIOS_MENU_LABEL } from "@/lib/oficios-menu";
import {
  LayoutDashboard,
  Users,
  Calendar,
  FileText,
  Recycle,
  LogOut,
  Leaf,
  ChevronDown,
  Briefcase,
  FolderKanban,
  FileCheck,
  ShoppingCart,
  UserCog,
  Book,
  FileSignature,
  ClipboardPenLine,
  Landmark,
  Droplets,
  Trees,
  FolderClock,
  FolderCheck,
  PlusSquare,
  Building,
  Contact,
  ClipboardCheck,
  SearchCheck,
  Link as LinkIcon,
  BookText,
  ShieldCheck,
  Building2,
  ListTree,
  FileQuestion,
  BookMarked,
  Shield,
  BookOpenCheck,
  Mountain,
  Bird,
  NotebookText,
  HardHat,
  MessagesSquare,
  Waves,
  Share2,
  Users2,
  Globe,
  ClipboardList,
  Signal,
  Settings,
  Bell,
  History,
  Folder,
  Mail,
  Send,
  Truck,
  List,
  LineChart,
  BarChart2,
  TrendingUp,
  FileDown,
  Palette,
  FileArchive,
  Bot,
  DatabaseZap,
  Workflow,
  Scale,
  Sparkles,
  Map,
  MapPinned,
  Crosshair,
  FileSpreadsheet,
  BookOpen,
  Smartphone,
  AlertTriangle,
} from "lucide-react";

/** Rótulo do grupo de menu (licenças, CAR, outorgas, fauna, monitoramento, etc.). */
export const DOCUMENTOS_AMBIENTAIS_MENU_LABEL = "Documentos Ambientais";

/** Rótulo do menu de IA (análises, assistente, relatórios de IA). */
export const IA_MENU_LABEL = "IA";

/** Rótulo do menu de vistorias em campo. */
export const VISTORIA_TECNICA_MENU_LABEL = "Vistoria Técnica";

/** Rótulo do menu de estudos técnicos (EIA, fauna, inventário, planos, mapas, etc.). */
export const ESTUDOS_TECNICOS_MENU_LABEL = "Estudos Técnicos";

export const allNavItems: NavItem[] = [
  {
    href: "/carteira",
    label: "Minha Carteira",
    icon: Briefcase,
    roles: ["consultor_representante", "client", "cliente_autonomo", "admin"],
  },
  {
    href: "/",
    label: "Painel",
    icon: LayoutDashboard,
    roles: [
      "admin",
      "client",
      "cliente_autonomo",
      "representative",
      "technical",
      "sales",
      "financial",
      "gestor",
      "supervisor",
      "diretor_fauna",
      "advogado",
    ],
  },
  {
    label: "Financeiro",
    icon: Briefcase,
    roles: [
      "admin",
      "financial",
      "sales",
      "client",
      "representative",
    ],
    subItems: [
      {
        href: "/bank-access",
        label: "Acesso Bancário",
        icon: Landmark,
        roles: ["admin", "financial"],
      },
      {
        href: "/clients",
        label: "Clientes",
        icon: Users,
        roles: ["admin", "sales", "financial"],
      },
      {
        href: "/contracts",
        label: "Contratos",
        icon: FileSignature,
        roles: [
          "admin",
          "financial",
          "sales",
          "client",
          "representative",
        ],
      },
      {
        href: "/financial/platform-subscription-contracts",
        label: "Contratos Plataforma",
        icon: FileText,
        roles: ["admin", "financial"],
      },
      {
        href: "/contracts-suppliers",
        label: "Contratos-Fornecedores",
        icon: FileSignature,
        roles: [
          "admin",
          "financial",
          "sales",
        ],
      },
      {
        href: "/financial/abc-curve",
        label: "Curva ABC",
        icon: LineChart,
        roles: ["admin", "financial"],
      },
      {
        href: "/financial/bens-patrimonio",
        label: "Bens e Patrimônio",
        icon: Building2,
        roles: ["admin", "financial"],
      },
      {
        href: "/financial/dre-contabil",
        label: "DRE Contábil",
        icon: BarChart2,
        roles: ["admin", "financial"],
      },
      {
        href: "/invoices",
        label: "Faturas",
        icon: FileText,
        roles: [
          "admin",
          "financial",
          "client",
          "representative",
        ],
      },
      {
        href: "/suppliers",
        label: "Fornecedores",
        icon: Truck,
        roles: ["admin", "financial"],
      },
      {
        href: "/cash-flow",
        label: "Lançamentos de Caixa",
        icon: Landmark,
        roles: ["admin", "financial"],
      },
      {
        href: "/external?url=https%3A%2F%2Fwww.nfse.gov.br%2FEmissorNacional%2FLogin%3FReturnUrl%3D%252fEmissorNacional&title=NFe-Eletr%C3%B4nica",
        label: "NFe-Eletrônica",
        icon: FileText,
        roles: ["admin", "financial"],
      },
      {
        href: "/commercial-proposals",
        label: "Orçamentos e Propostas",
        icon: ClipboardPenLine,
        roles: [
          "admin",
          "financial",
          "sales",
          "client",
          "cliente_autonomo",
          "representative",
        ],
      },
      {
        href: "/financial/painel",
        label: "Painel Financeiro",
        icon: BarChart2,
        roles: ["admin", "financial"],
      },
      {
        href: "/financial/projetos-roi",
        label: "Projetos & ROI",
        icon: TrendingUp,
        roles: ["admin", "financial", "sales"],
      },
      {
        href: "/financial/fluxo-projetado",
        label: "Fluxo de Caixa Projetado",
        icon: TrendingUp,
        roles: ["admin", "financial"],
      },
      {
        href: "/financial/conciliacao",
        label: "Conciliação Bancária",
        icon: Landmark,
        roles: ["admin", "financial"],
      },
      {
        href: "/financial/abc-servicos",
        label: "Curva ABC Serviços",
        icon: BarChart2,
        roles: ["admin", "financial"],
      },
      {
        href: "/financial/abc-fornecedores",
        label: "Curva ABC Fornecedores",
        icon: BarChart2,
        roles: ["admin", "financial"],
      },
      {
        href: "/financial/orcamento",
        label: "Orçamento Anual",
        icon: FileSpreadsheet,
        roles: ["admin", "financial"],
      },
      {
        href: "/financial/export-contabil",
        label: "Exportação Contábil",
        icon: FileDown,
        roles: ["admin", "financial"],
      },
      {
        href: "/studies/assistant?tipo=financeiro",
        label: "Assistente Financeiro (IA)",
        icon: Sparkles,
        roles: ["admin", "financial"],
      },
      {
        href: "/services",
        label: "Tabela de Serviços",
        icon: List,
        roles: ["admin", "financial"],
      },
    ],
  },
  {
    label: "Cadastro",
    icon: Book,
    roles: [
      "admin",
      "technical",
      "gestor",
      "diretor_fauna",
      "supervisor",
      "financial",
      "sales",
      "client",
      "cliente_autonomo",
      "representative",
      "advogado",
    ],
    subItems: [
      {
        href: "/empreendedores",
        label: "Empreendedores",
        icon: Contact,
        roles: [
          "admin",
          "technical",
          "gestor",
          "diretor_fauna",
          "supervisor",
          "financial",
          "sales",
          "client",
          "cliente_autonomo",
          "representative",
          "advogado",
        ],
      },
      {
        href: "/projects",
        label: "Empreendimentos",
        icon: Building,
        roles: [
          "admin",
          "technical",
          "gestor",
          "diretor_fauna",
          "supervisor",
          "financial",
          "sales",
          "client",
          "cliente_autonomo",
          "representative",
          "advogado",
        ],
      },
      {
        href: "/responsible-company",
        label: "Empresas",
        icon: Building2,
        roles: [
          "admin",
          "technical",
          "gestor",
          "diretor_fauna",
          "supervisor",
          "financial",
          "sales",
          "client",
          "cliente_autonomo",
          "representative",
          "advogado",
        ],
      },
    ],
  },
  {
    label: DOCUMENTOS_AMBIENTAIS_MENU_LABEL,
    icon: Recycle,
    roles: [
      "admin",
      "client",
      "cliente_autonomo",
      "representative",
      "technical",
      "gestor",
      "supervisor",
      "diretor_fauna",
      "advogado",
    ],
    subItems: [
      {
        href: "/car",
        label: "CAR",
        icon: FileText,
        roles: [
          "admin",
          "client",
      "cliente_autonomo",
          "representative",
          "gestor",
          "supervisor",
          "technical",
          "advogado",
        ],
      },
      {
        href: "/compliance",
        label: "Condicionantes",
        icon: ClipboardCheck,
        roles: [
          "admin",
          "client",
      "cliente_autonomo",
          "representative",
          "gestor",
          "supervisor",
          "technical",
          "advogado",
        ],
      },
      {
        href: "/ctf-ibama",
        label: "CTF/IBAMA",
        icon: ShieldCheck,
        roles: [
          "admin",
          "client",
          "cliente_autonomo",
          "representative",
          "gestor",
          "supervisor",
          "technical",
          "advogado",
        ],
      },
      {
        href: "/intervencoes",
        label: "DAIA's",
        icon: Trees,
        roles: [
          "admin",
          "client",
      "cliente_autonomo",
          "representative",
          "gestor",
          "supervisor",
          "technical",
          "advogado",
        ],
      },
      {
        href: "/fauna",
        label: "Fauna",
        icon: Bird,
        roles: [
          "admin",
          "client",
      "cliente_autonomo",
          "representative",
          "technical",
          "gestor",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        href: "/licenses",
        label: "Licenças",
        icon: FileCheck,
        roles: [
          "admin",
          "client",
      "cliente_autonomo",
          "representative",
          "gestor",
          "supervisor",
          "technical",
          "advogado",
        ],
      },
      {
        href: "/mtr-declaracao",
        label: "MTR-Declaração",
        icon: Truck,
        roles: [
          "admin",
          "client",
      "cliente_autonomo",
          "representative",
          "gestor",
          "supervisor",
          "technical",
          "advogado",
        ],
      },
      {
        href: "/documentos-ambientais/pasta-cliente",
        label: "Pasta do cliente",
        icon: Folder,
        roles: [
          "admin",
          "technical",
          "gestor",
          "supervisor",
          "financial",
        ],
      },
      {
        label: "Monitoramento de Outorga",
        icon: BookMarked,
        roles: [
          "admin",
          "client",
      "cliente_autonomo",
          "representative",
          "gestor",
          "supervisor",
          "technical",
          "advogado",
        ],
        subItems: [
          {
            href: "/monitoring/manual",
            label: "Lançamento Manual",
            icon: ClipboardList,
            roles: [
              "admin",
              "client",
      "cliente_autonomo",
              "representative",
              "gestor",
              "supervisor",
              "technical",
              "advogado",
            ],
          },
          {
            href: "/monitoring/telemetric",
            label: "Telemetria (Real-time)",
            icon: Signal,
            roles: [
              "admin",
              "client",
      "cliente_autonomo",
              "representative",
              "gestor",
              "supervisor",
              "technical",
              "advogado",
            ],
          },
        ],
      },
      {
        href: "/outorgas",
        label: "Outorgas",
        icon: Droplets,
        roles: [
          "admin",
          "client",
      "cliente_autonomo",
          "representative",
          "gestor",
          "supervisor",
          "technical",
          "advogado",
        ],
      },
      {
        href: "/usos-insignificantes",
        label: "Usos Insignificantes",
        icon: Waves,
        roles: [
          "admin",
          "client",
      "cliente_autonomo",
          "representative",
          "gestor",
          "supervisor",
          "technical",
          "advogado",
        ],
      },
      {
        href: "/inspections/reports",
        label: "Relatórios de Campo",
        icon: FileText,
        roles: [
          "admin",
          "client",
          "cliente_autonomo",
          "representative",
          "gestor",
          "supervisor",
          "technical",
          "advogado",
        ],
      },
    ],
  },
  {
    label: MULTAS_E_DEFESAS_MENU_LABEL,
    icon: Scale,
    roles: ["admin", "advogado", "technical", "gestor", "supervisor"],
    subItems: [
      {
        href: MULTAS_DEFESAS_PATH,
        label: MULTAS_DEFESAS_LIST_LABEL,
        icon: List,
        roles: ["admin", "advogado", "technical", "gestor", "supervisor"],
      },
      {
        href: MULTAS_DEFESAS_NOVA_PATH,
        label: MULTAS_DEFESAS_NOVA_LABEL,
        icon: PlusSquare,
        roles: ["admin", "advogado", "technical", "gestor", "supervisor"],
      },
    ],
  },
  {
    label: VISTORIA_TECNICA_MENU_LABEL,
    icon: SearchCheck,
    roles: [
      "admin",
      "technical",
      "gestor",
      "supervisor",
      "advogado",
    ],
    subItems: [
      {
        href: "/inspections",
        label: "Consultar vistorias",
        icon: List,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        href: "/inspections/new",
        label: "Nova vistoria",
        icon: PlusSquare,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        href: "/inspections/reports",
        label: "Relatórios de Campo",
        icon: FileText,
        roles: [
          "admin",
          "gestor",
          "supervisor",
          "technical",
          "advogado",
        ],
      },
    ],
  },
  {
    label: LICENCIAMENTO_MENU_LABEL,
    icon: ClipboardList,
    roles: [
      "admin",
      "technical",
      "gestor",
      "supervisor",
      "advogado",
      "client",
      "representative",
    ],
    subItems: [
      {
        href: "/requests",
        label: LICENCIAMENTO_LIST_SUBITEM_LABEL,
        icon: List,
        roles: [
          "admin",
          "technical",
          "gestor",
          "supervisor",
          "advogado",
          "client",
          "representative",
        ],
      },
      {
        href: "/requests/new",
        label: LICENCIAMENTO_NEW_SUBITEM_LABEL,
        icon: PlusSquare,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
    ],
  },
  {
    label: IA_MENU_LABEL,
    icon: Sparkles,
    roles: [
      "admin",
      "financial",
      "technical",
      "gestor",
      "supervisor",
      "diretor_fauna",
      "advogado",
    ],
    subItems: [
      {
        href: "/studies/assistant?tipo=mira",
        label: "Águas / MIRA-IGAM",
        icon: Droplets,
        roles: [
          "admin",
          "technical",
          "gestor",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        href: "/analise-ambiental",
        label: "Análise Geoespacial (IA)",
        icon: Globe,
        roles: [
          "admin",
          "technical",
          "gestor",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        href: "/studies/analise-socioambiental",
        label: "Análise Socioambiental",
        icon: FileText,
        roles: [
          "admin",
          "technical",
          "gestor",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        href: "/studies/assistant?tipo=mcp",
        label: "Cruzamento de dados",
        icon: Workflow,
        roles: [
          "admin",
          "technical",
          "gestor",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        href: "/studies/assistant?tipo=financeiro",
        label: "Custos e contratos",
        icon: BarChart2,
        roles: ["admin", "technical", "gestor", "supervisor", "diretor_fauna", "advogado"],
      },
      {
        href: "/studies/assistant?tipo=geral",
        label: "Legislação e estudos",
        icon: BookOpenCheck,
        roles: [
          "admin",
          "technical",
          "gestor",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        href: "/reporting",
        label: "Relatórios de IA",
        icon: Recycle,
        roles: ["admin", "financial"],
      },
      {
        href: "/studies/assistant?tipo=rag",
        label: "Síntese de texto",
        icon: FileArchive,
        roles: [
          "admin",
          "technical",
          "gestor",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        label: "Automações",
        icon: Bot,
        roles: ["admin"],
        subItems: [
          {
            href: "/ai-lab/automations",
            label: "Automações IA",
            icon: Bot,
            roles: ["admin"],
          },
        ],
      },
    ],
  },
  {
    label: ESTUDOS_TECNICOS_MENU_LABEL,
    icon: BookText,
    roles: [
      "admin",
      "technical",
      "gestor",
      "supervisor",
      "diretor_fauna",
      "advogado",
    ],
    subItems: [
      {
        href: "/studies/educacao-ambiental",
        label: "Programa de Educação Ambiental",
        icon: BookOpenCheck,
        roles: [
          "admin",
          "technical",
          "gestor",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        href: "/studies/acao-emergencial",
        label: "Programa de Ação Emergencial",
        icon: AlertTriangle,
        roles: [
          "admin",
          "technical",
          "gestor",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        href: "/studies/eia-rima",
        label: "EIA/RIMA",
        icon: FileQuestion,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        href: "/studies/cavidades",
        label: "Estudo de Cavidades",
        icon: Mountain,
        roles: [
          "admin",
          "technical",
          "gestor",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        href: "/studies/fauna",
        label: "Estudos de Fauna",
        icon: Bird,
        roles: [
          "admin",
          "technical",
          "gestor",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        href: "/studies/ide-sisemanet",
        label: "IDE-SisemaNet",
        icon: MapPinned,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        label: "Inventário Florestal",
        icon: ListTree,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
        subItems: [
          {
            href: "/studies/inventario",
            label: "Inventário Florestal",
            icon: ListTree,
            roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
          },
          {
            href: "/coleta-campo",
            label: "Coleta de campo",
            icon: Smartphone,
            roles: ["admin", "technical", "gestor", "supervisor", "diretor_fauna"],
          },
        ],
      },
      {
        href: "/studies/las-ras",
        label: "LAS-RAS",
        icon: FileSignature,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        href: "/studies/reanalise",
        label: "Reanálise",
        icon: FileSignature,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        href: "/studies/procuracao",
        label: "Procuração",
        icon: FileSignature,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        href: "/studies/mapas",
        label: "Mapas",
        icon: Map,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        label: "Outorgas (processos)",
        icon: Droplets,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
        subItems: [
          {
            href: "/studies/outorgas",
            label: "Processos",
            icon: ClipboardList,
            roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
          },
          {
            href: "/studies/outorgas/new",
            label: "Nova outorga",
            icon: PlusSquare,
            roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
          },
        ],
      },
      {
        href: "/studies/pca",
        label: "PCA",
        icon: BookMarked,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        href: "/studies/pia",
        label: "PIA",
        icon: FileCheck,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        href: "/studies/prada",
        label: "PRADA",
        icon: Leaf,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        href: "/studies/barragem",
        label: "Projeto Técnico de Barragem",
        icon: Building2,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        href: "/studies/piscinao-off-stream",
        label: "Cadastro de Piscinão (off-stream)",
        icon: Waves,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        href: "/studies/ptrf",
        label: "PTRF",
        icon: Trees,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        href: "/studies/rca",
        label: "RCA",
        icon: NotebookText,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        href: "/studies/relatorios-diversos",
        label: "Relatórios Diversos",
        icon: FileArchive,
        roles: [
          "admin",
          "technical",
          "gestor",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        href: "/studies/mtr",
        label: "MTR-MG (resíduos)",
        icon: Recycle,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        label: "Compensação Ambiental",
        icon: Scale,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
        subItems: [
          {
            href: "/studies/compensacao-ambiental",
            label: "Visão geral",
            icon: Scale,
            roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
          },
          {
            href: "/studies/compensacao-ambiental/especies",
            label: "Espécies protegidas",
            icon: Trees,
            roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
          },
          {
            href: "/studies/compensacao-ambiental/snuc",
            label: "SNUC",
            icon: Scale,
            roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
          },
          {
            href: "/studies/compensacao-ambiental/mata-atlantica",
            label: "Mata Atlântica",
            icon: Leaf,
            roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
          },
          {
            href: "/studies/compensacao-ambiental/mineraria",
            label: "Minerária",
            icon: Building2,
            roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
          },
          {
            href: "/studies/compensacao-ambiental/app",
            label: "Intervenção em APP",
            icon: Droplets,
            roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
          },
        ],
      },
      {
        href: "/studies/reserva-legal",
        label: "Reserva Legal",
        icon: ShieldCheck,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        href: "/studies/seguranca-barragens",
        label: "Segurança de Barragens",
        icon: Shield,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
    ],
  },
  {
    label: "Georeferenciamento",
    icon: Crosshair,
    roles: [
      "admin",
      "gestor",
      "supervisor",
      "diretor_fauna",
      "advogado",
    ],
    subItems: [
      {
        href: "/georeferenciamento",
        label: "Painel",
        icon: LayoutDashboard,
        roles: ["admin", "gestor", "supervisor", "diretor_fauna", "advogado"],
      },
      {
        href: "/georeferenciamento/processos",
        label: GEOREF_TRAMITES_SUBMENU_LABEL,
        icon: FolderKanban,
        roles: ["admin", "gestor", "supervisor", "diretor_fauna", "advogado"],
      },
      {
        href: "/georeferenciamento/rural",
        label: "Rural (SIGEF/INCRA)",
        icon: Trees,
        roles: ["admin", "gestor", "supervisor", "diretor_fauna", "advogado"],
      },
      {
        href: "/georeferenciamento/urbano",
        label: "Urbano (cartório)",
        icon: Building2,
        roles: ["admin", "gestor", "supervisor", "diretor_fauna", "advogado"],
      },
      {
        href: "/georeferenciamento/ambiental",
        label: "CAR / SICAR",
        icon: Leaf,
        roles: ["admin", "gestor", "supervisor", "diretor_fauna", "advogado"],
      },
      {
        href: "/georeferenciamento/campo",
        label: "Campo e levantamento",
        icon: Crosshair,
        roles: ["admin", "gestor", "supervisor", "diretor_fauna", "advogado"],
      },
      {
        href: "/georeferenciamento/documentos",
        label: "Documentação técnica",
        icon: FileSpreadsheet,
        roles: ["admin", "gestor", "supervisor", "diretor_fauna", "advogado"],
      },
      {
        href: "/georeferenciamento/validacoes",
        label: "Validações",
        icon: Scale,
        roles: ["admin", "gestor", "supervisor", "diretor_fauna", "advogado"],
      },
      {
        href: "/georeferenciamento/registro",
        label: "Cartório e registro",
        icon: BookOpen,
        roles: ["admin", "gestor", "supervisor", "diretor_fauna", "advogado"],
      },
      {
        href: "/georeferenciamento/referencias",
        label: "Referências normativas",
        icon: BookOpenCheck,
        roles: ["admin", "gestor", "supervisor", "diretor_fauna", "advogado"],
      },
    ],
  },
  {
    label: "Vendas & CRM",
    icon: ShoppingCart,
    roles: ["admin", "sales", "supervisor", "financial"],
    subItems: [
      {
        href: "/crm/alerts",
        label: "Alertas & Notificações",
        icon: Bell,
        roles: ["admin", "sales", "supervisor", "financial"],
      },
      {
        href: "/crm/settings",
        label: "Configurações CRM",
        icon: Settings,
        roles: ["admin", "sales", "supervisor", "financial"],
      },
      {
        href: "/crm/team",
        label: "Equipe & Desempenho",
        icon: Users,
        roles: ["admin", "sales", "supervisor", "financial"],
      },
      {
        href: "/crm/clients",
        label: "Gestão de Clientes",
        icon: Users,
        roles: ["admin", "sales", "supervisor", "financial"],
      },
      {
        href: "/social-media",
        label: "Mídias Sociais",
        icon: Share2,
        roles: ["admin", "sales", "supervisor", "financial"],
      },
      {
        href: "/crm/opportunities",
        label: "Oportunidades & Pipeline",
        icon: FolderKanban,
        roles: ["admin", "sales", "supervisor", "financial"],
      },
      {
        href: "/crm",
        label: "Painel de Vendas",
        icon: LayoutDashboard,
        roles: ["admin", "sales", "supervisor", "financial"],
      },
      {
        href: "/crm/reports",
        label: "Relatórios & Análises",
        icon: BarChart2,
        roles: ["admin", "sales", "supervisor", "financial"],
      },
      {
        href: "/crm/proposals",
        label: "Vendas & Propostas",
        icon: FileText,
        roles: ["admin", "sales", "supervisor", "financial"],
      },
    ],
  },
  {
    href: "/external?url=https%3A%2F%2Fconsultoriapimenta.com.br%3A2096%2F&title=Webmail",
    label: "Webmail",
    icon: Send,
    roles: [
      "admin",
      "technical",
      "sales",
      "financial",
      "gestor",
      "supervisor",
      "diretor_fauna",
      "advogado",
    ],
  },
  {
    href: "/oficios",
    label: OFICIOS_MENU_LABEL,
    icon: Send,
    roles: [
      "admin",
      "client",
      "cliente_autonomo",
      "technical",
      "sales",
      "financial",
      "gestor",
      "supervisor",
      "diretor_fauna",
      "advogado",
    ],
  },
  {
    label: "Acessos Governamentais",
    icon: LinkIcon,
    roles: [
      "admin",
      "technical",
      "gestor",
      "financial",
      "sales",
      "supervisor",
      "diretor_fauna",
      "advogado",
    ],
    subItems: [
      {
        href: "/external?url=https%3A%2F%2Fsistemas.meioambiente.mg.gov.br%2Fconsulta-intervencao%2Fsite%2Flistar-decisoes&title=Consulta%20Interven%C3%A7%C3%A3o%20Ambiental",
        label: "Consulta Intervenção Ambiental",
        icon: BookText,
        roles: [
          "admin",
          "technical",
          "gestor",
          "financial",
          "sales",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        href: "/external?url=https%3A%2F%2Fsistemas.meioambiente.mg.gov.br%2Flicenciamento%2Fsite%2Fconsulta-licenca&title=Consulta%20de%20Licen%C3%A7as",
        label: "Consulta Licenciamento",
        icon: BookText,
        roles: [
          "admin",
          "technical",
          "gestor",
          "financial",
          "sales",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        href: "/external?url=https%3A%2F%2Fsistemas.meioambiente.mg.gov.br%2Flicenciamento%2Fsite%2Flista-outorgas&title=Consulta%20de%20Outorgas",
        label: "Consulta Outorgas",
        icon: BookText,
        roles: [
          "admin",
          "technical",
          "gestor",
          "financial",
          "sales",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        href: "/external?url=https%3A%2F%2Fservicos.ibama.gov.br%2Fctf%2F&title=CTF%2FIBAMA&newTab=true",
        label: "CTF/IBAMA",
        icon: LinkIcon,
        roles: [
          "admin",
          "technical",
          "gestor",
          "financial",
          "sales",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        href: "/external?url=https%3A%2F%2Fvisualizador.idesisema.meioambiente.mg.gov.br%2F&title=IDE-SisemaNet-MG",
        label: "IDE-SisemaNet-MG",
        icon: Globe,
        roles: ["admin", "technical", "gestor", "supervisor", "diretor_fauna", "advogado"],
      },
      {
        href: "/external?url=https%3A%2F%2Fsei.ibama.gov.br%2Fcontrolador_externo.php%3Facao%3Dusuario_externo_logar%26id_orgao_acesso_externo%3D0&title=SEI-IBAMA&newTab=true",
        label: "SEI-IBAMA",
        icon: LinkIcon,
        roles: [
          "admin",
          "technical",
          "gestor",
          "financial",
          "sales",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        href: "/external?url=https%3A%2F%2Fwww.sei.mg.gov.br%2Fsei%2Fcontrolador_externo.php%3Facao%3Dusuario_externo_logar%26id_orgao_acesso_externo%3D0&title=SEI-MG&newTab=true",
        label: "SEI-MG",
        icon: LinkIcon,
        roles: [
          "admin",
          "technical",
          "gestor",
          "financial",
          "sales",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        href: "/external?url=https%3A%2F%2Fecosistemas.meioambiente.mg.gov.br%2Fportalseguranca%2Flogin&title=SLA-Ecossistemas-MG&newTab=true",
        label: "SLA-Ecossistemas/MG",
        icon: LinkIcon,
        roles: [
          "admin",
          "technical",
          "gestor",
          "financial",
          "sales",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
    ],
  },
  {
    label: "Configurações",
    icon: Settings,
    roles: [
      "admin",
      "client",
      "cliente_autonomo",
      "representative",
      "technical",
      "sales",
      "financial",
      "gestor",
      "supervisor",
      "diretor_fauna",
      "advogado",
    ],
    subItems: [
      {
        href: "/configuracoes/mcp-rag",
        label: "MCP + RAG / Inteligência do Sistema",
        icon: DatabaseZap,
        roles: ["admin"],
      },
      {
        href: "/settings/deleted-backups",
        label: "Backup de Dados Apagados",
        icon: History,
        roles: ["admin", "supervisor"],
      },
      {
        href: "/settings/files",
        label: "Explorador de Arquivos",
        icon: Folder,
        roles: ["admin"],
      },
      {
        href: "/consultas",
        label: "Consultas Técnicas",
        icon: FileQuestion,
        roles: ["admin", "technical", "gestor", "supervisor", "financial"],
      },
      {
        href: "/laudos",
        label: "Laudos",
        icon: BookOpenCheck,
        roles: ["admin", "technical", "gestor", "supervisor"],
      },
      {
        href: "/canais",
        label: "Canais (WhatsApp/IG)",
        icon: MessagesSquare,
        roles: ["admin"],
      },
      {
        href: "/settings#identidade-visual",
        label: "Identidade Visual",
        icon: Palette,
        roles: ["admin"],
      },
      {
        href: "/settings/company",
        label: "Informações da Empresa",
        icon: Building,
        roles: ["admin"],
      },
      {
        href: "/audit-log",
        label: "Log de Auditoria",
        icon: History,
        roles: ["admin", "supervisor"],
      },
      {
        href: "/technical-responsible",
        label: "Responsáveis Técnicos",
        icon: HardHat,
        roles: ["admin", "supervisor", "gestor"],
      },
      {
        href: "/settings/appearance",
        label: "Aparência",
        icon: Palette,
        roles: [
          "admin",
          "client",
          "cliente_autonomo",
          "representative",
          "technical",
          "sales",
          "financial",
          "gestor",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        href: "/settings/templates",
        label: "Templates",
        icon: FileText,
        roles: ["admin"],
      },
      {
        href: "/users",
        label: "Usuários",
        icon: UserCog,
        roles: [
          "admin",
          "client",
          "cliente_autonomo",
          "representative",
          "sales",
          "supervisor",
          "technical",
          "gestor",
          "diretor_fauna",
          "financial",
          "advogado",
        ],
      },
    ],
  },
  {
    href: "/calendar",
    label: "Agenda",
    icon: Calendar,
    roles: [
      "admin",
      "technical",
      "financial",
      "gestor",
      "client",
      "cliente_autonomo",
      "representative",
      "supervisor",
      "sales",
      "diretor_fauna",
      "advogado",
    ],
  },
];
