"use client";

import type { NavItem } from "@/lib/types";
import {
  buildGestaoProcessosNavSubItems,
  GESTAO_PROCESSOS_MENU_LABEL,
  GESTAO_PROCESSOS_MENU_ROLES,
} from "@/lib/gestao-processos-menu";
import {
  MULTAS_DEFESAS_LIST_LABEL,
  MULTAS_DEFESAS_NOVA_LABEL,
  MULTAS_DEFESAS_NOVA_PATH,
  MULTAS_DEFESAS_PATH,
  MULTAS_E_DEFESAS_MENU_LABEL,
} from "@/lib/multas-defesas-menu";
import { OFICIOS_MENU_LABEL } from "@/lib/oficios-menu";
import { buildFinanceiroNfeNavItem } from "@/lib/financeiro-external-menu";
import {
  buildGovAccessNavSubItems,
  GOV_ACCESS_MENU_LABEL,
} from "@/lib/gov-access-menu";
import { buildPcaNavSubItems, PCA_MENU_LABEL, PCA_NAV_ROLES } from "@/lib/pca-menu";
import { buildRcaNavSubItems, RCA_MENU_LABEL, RCA_NAV_ROLES } from "@/lib/rca-menu";
import {
  buildGeorefNavSubItems,
  GEOREF_MENU_LABEL,
  GEOREF_NAV_ROLES,
} from "@/lib/georef-menu";
import { buildIaNavSubItems, IA_MENU_LABEL } from "@/lib/ia-menu";
import { buildCrmNavSubItems, CRM_MENU_LABEL, CRM_NAV_ROLES } from "@/lib/crm-menu";
import {
  DOCUMENTOS_AMBIENTAIS_MENU_LABEL,
  ESTUDOS_TECNICOS_MENU_LABEL,
  VISTORIA_TECNICA_MENU_LABEL,
} from "@/lib/navigation-labels";
import {
  LayoutDashboard,
  Users,
  Calendar,
  FileText,
  Recycle,
  LogOut,
  Leaf,
  ChevronDown,
  Briefcase,
  FolderKanban,
  FileCheck,
  ShoppingCart,
  UserCog,
  Book,
  FileSignature,
  ClipboardPenLine,
  Landmark,
  Droplets,
  Trees,
  FolderClock,
  FolderCheck,
  PlusSquare,
  Building,
  Contact,
  ClipboardCheck,
  SearchCheck,
  LinkIcon,
  BookText,
  ShieldCheck,
  Building2,
  ListTree,
  FileQuestion,
  BookMarked,
  Shield,
  BookOpenCheck,
  Mountain,
  Bird,
  NotebookText,
  HardHat,
  MessagesSquare,
  Waves,
  Share2,
  Globe,
  ClipboardList,
  Signal,
  Settings,
  Bell,
  History,
  Folder,
  Mail,
  Send,
  Truck,
  LayoutGrid,
  List,
  LineChart,
  BarChart2,
  TrendingUp,
  FileDown,
  Palette,
  FileArchive,
  Bot,
  DatabaseZap,
  Workflow,
  Scale,
  Sparkles,
  Map,
  MapPinned,
  Crosshair,
  FileSpreadsheet,
  BookOpen,
  Smartphone,
  AlertTriangle,
  Bug,
} from "@/lib/navigation-icons";

/** Rótulos re-exportados para compatibilidade — preferir `@/lib/navigation-labels` no shell. */
export {
  DOCUMENTOS_AMBIENTAIS_MENU_LABEL,
  ESTUDOS_TECNICOS_MENU_LABEL,
  VISTORIA_TECNICA_MENU_LABEL,
} from "@/lib/navigation-labels";

export { IA_MENU_LABEL };

export const allNavItems: NavItem[] = [
  {
    href: "/carteira",
    label: "Minha Carteira",
    icon: Briefcase,
    roles: ["consultor_representante", "client", "cliente_autonomo", "admin"],
  },
  {
    href: "/",
    label: "Painel",
    icon: LayoutDashboard,
    roles: [
      "admin",
      "client",
      "cliente_autonomo",
      "representative",
      "technical",
      "sales",
      "financial",
      "gestor",
      "supervisor",
      "diretor_fauna",
      "advogado",
    ],
  },
  {
    label: "Financeiro",
    icon: Briefcase,
    roles: [
      "admin",
      "financial",
      "sales",
      "client",
      "representative",
    ],
    subItems: [
      {
        href: "/bank-access",
        label: "Acesso Bancário",
        icon: Landmark,
        roles: ["admin", "financial"],
      },
      {
        href: "/clients",
        label: "Clientes",
        icon: Users,
        roles: ["admin", "sales", "financial"],
      },
      {
        href: "/contracts",
        label: "Contratos",
        icon: FileSignature,
        roles: [
          "admin",
          "financial",
          "sales",
          "client",
          "representative",
        ],
      },
      {
        href: "/financial/platform-subscription-contracts",
        label: "Contratos Plataforma",
        icon: FileText,
        roles: ["admin", "financial"],
      },
      {
        href: "/contracts-suppliers",
        label: "Contratos-Fornecedores",
        icon: FileSignature,
        roles: [
          "admin",
          "financial",
          "sales",
        ],
      },
      {
        href: "/financial/abc-curve",
        label: "Curva ABC",
        icon: LineChart,
        roles: ["admin", "financial"],
      },
      {
        href: "/financial/bens-patrimonio",
        label: "Bens e Patrimônio",
        icon: Building2,
        roles: ["admin", "financial"],
      },
      {
        href: "/financial/dre-contabil",
        label: "DRE Contábil",
        icon: BarChart2,
        roles: ["admin", "financial"],
      },
      {
        href: "/invoices",
        label: "Faturas",
        icon: FileText,
        roles: [
          "admin",
          "financial",
          "client",
          "representative",
        ],
      },
      {
        href: "/suppliers",
        label: "Fornecedores",
        icon: Truck,
        roles: ["admin", "financial"],
      },
      {
        href: "/cash-flow",
        label: "Lançamentos de Caixa",
        icon: Landmark,
        roles: ["admin", "financial"],
      },
      buildFinanceiroNfeNavItem(),
      {
        href: "/commercial-proposals",
        label: "Orçamentos e Propostas",
        icon: ClipboardPenLine,
        roles: [
          "admin",
          "financial",
          "sales",
          "client",
          "cliente_autonomo",
          "representative",
        ],
      },
      {
        href: "/financial/painel",
        label: "Painel Financeiro",
        icon: BarChart2,
        roles: ["admin", "financial"],
      },
      {
        href: "/financial/projetos-roi",
        label: "Projetos & ROI",
        icon: TrendingUp,
        roles: ["admin", "financial", "sales"],
      },
      {
        href: "/financial/fluxo-projetado",
        label: "Fluxo de Caixa Projetado",
        icon: TrendingUp,
        roles: ["admin", "financial"],
      },
      {
        href: "/financial/conciliacao",
        label: "Conciliação Bancária",
        icon: Landmark,
        roles: ["admin", "financial"],
      },
      {
        href: "/financial/billing-debug",
        label: "Debug PIX Assinatura",
        icon: Bug,
        roles: ["admin", "financial", "supervisor"],
      },
      {
        href: "/financial/abc-servicos",
        label: "Curva ABC Serviços",
        icon: BarChart2,
        roles: ["admin", "financial"],
      },
      {
        href: "/financial/abc-fornecedores",
        label: "Curva ABC Fornecedores",
        icon: BarChart2,
        roles: ["admin", "financial"],
      },
      {
        href: "/financial/orcamento",
        label: "Orçamento Anual",
        icon: FileSpreadsheet,
        roles: ["admin", "financial"],
      },
      {
        href: "/financial/export-contabil",
        label: "Exportação Contábil",
        icon: FileDown,
        roles: ["admin", "financial"],
      },
      {
        href: "/studies/assistant?tipo=financeiro",
        label: "Assistente Financeiro (IA)",
        icon: Sparkles,
        roles: ["admin", "financial"],
      },
      {
        href: "/services",
        label: "Tabela de Serviços",
        icon: List,
        roles: ["admin", "financial"],
      },
    ],
  },
  {
    label: "Cadastro",
    icon: Book,
    roles: [
      "admin",
      "technical",
      "gestor",
      "diretor_fauna",
      "supervisor",
      "financial",
      "sales",
      "client",
      "cliente_autonomo",
      "representative",
      "advogado",
    ],
    subItems: [
      {
        href: "/users",
        label: "Usuários",
        icon: UserCog,
        roles: [
          "admin",
          "client",
          "cliente_autonomo",
          "representative",
          "sales",
          "supervisor",
          "technical",
          "gestor",
          "diretor_fauna",
          "financial",
          "advogado",
        ],
      },
      {
        href: "/empreendedores",
        label: "Empreendedores",
        icon: Contact,
        roles: [
          "admin",
          "technical",
          "gestor",
          "diretor_fauna",
          "supervisor",
          "financial",
          "sales",
          "client",
          "cliente_autonomo",
          "representative",
          "advogado",
        ],
      },
      {
        href: "/projects",
        label: "Empreendimentos",
        icon: Building,
        roles: [
          "admin",
          "technical",
          "gestor",
          "diretor_fauna",
          "supervisor",
          "financial",
          "sales",
          "client",
          "cliente_autonomo",
          "representative",
          "advogado",
        ],
      },
      {
        href: "/responsible-company",
        label: "Empresas",
        icon: Building2,
        roles: [
          "admin",
          "technical",
          "gestor",
          "diretor_fauna",
          "supervisor",
          "financial",
          "sales",
          "client",
          "cliente_autonomo",
          "representative",
          "advogado",
        ],
      },
    ],
  },
  {
    label: DOCUMENTOS_AMBIENTAIS_MENU_LABEL,
    icon: Recycle,
    roles: [
      "admin",
      "client",
      "cliente_autonomo",
      "representative",
      "technical",
      "gestor",
      "supervisor",
      "diretor_fauna",
      "advogado",
    ],
    subItems: [
      {
        href: "/car",
        label: "CAR",
        icon: FileText,
        roles: [
          "admin",
          "client",
      "cliente_autonomo",
          "representative",
          "gestor",
          "supervisor",
          "technical",
          "advogado",
        ],
      },
      {
        href: "/compliance",
        label: "Condicionantes",
        icon: ClipboardCheck,
        roles: [
          "admin",
          "client",
      "cliente_autonomo",
          "representative",
          "gestor",
          "supervisor",
          "technical",
          "advogado",
        ],
      },
      {
        href: "/ctf-ibama",
        label: "CTF/IBAMA",
        icon: ShieldCheck,
        roles: [
          "admin",
          "client",
          "cliente_autonomo",
          "representative",
          "gestor",
          "supervisor",
          "technical",
          "advogado",
        ],
      },
      {
        href: "/intervencoes",
        label: "DAIA's",
        icon: Trees,
        roles: [
          "admin",
          "client",
      "cliente_autonomo",
          "representative",
          "gestor",
          "supervisor",
          "technical",
          "advogado",
        ],
      },
      {
        href: "/fauna",
        label: "Fauna",
        icon: Bird,
        roles: [
          "admin",
          "client",
      "cliente_autonomo",
          "representative",
          "technical",
          "gestor",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        href: "/licenses",
        label: "Licenças",
        icon: FileCheck,
        roles: [
          "admin",
          "client",
      "cliente_autonomo",
          "representative",
          "gestor",
          "supervisor",
          "technical",
          "advogado",
        ],
      },
      {
        href: "/mtr-declaracao",
        label: "MTR-Declaração",
        icon: Truck,
        roles: [
          "admin",
          "client",
      "cliente_autonomo",
          "representative",
          "gestor",
          "supervisor",
          "technical",
          "advogado",
        ],
      },
      {
        href: "/documentos-ambientais/pasta-cliente",
        label: "Pasta do cliente",
        icon: Folder,
        roles: [
          "admin",
          "technical",
          "gestor",
          "supervisor",
          "financial",
        ],
      },
      {
        label: "Monitoramento de Outorga",
        icon: BookMarked,
        roles: [
          "admin",
          "client",
      "cliente_autonomo",
          "representative",
          "gestor",
          "supervisor",
          "technical",
          "advogado",
        ],
        subItems: [
          {
            href: "/monitoring/manual",
            label: "Lançamento Manual",
            icon: ClipboardList,
            roles: [
              "admin",
              "client",
      "cliente_autonomo",
              "representative",
              "gestor",
              "supervisor",
              "technical",
              "advogado",
            ],
          },
          {
            href: "/monitoring/telemetric",
            label: "Telemetria (Real-time)",
            icon: Signal,
            roles: [
              "admin",
              "client",
      "cliente_autonomo",
              "representative",
              "gestor",
              "supervisor",
              "technical",
              "advogado",
            ],
          },
        ],
      },
      {
        href: "/outorgas",
        label: "Outorgas",
        icon: Droplets,
        roles: [
          "admin",
          "client",
      "cliente_autonomo",
          "representative",
          "gestor",
          "supervisor",
          "technical",
          "advogado",
        ],
      },
      {
        href: "/usos-insignificantes",
        label: "Usos Insignificantes",
        icon: Waves,
        roles: [
          "admin",
          "client",
      "cliente_autonomo",
          "representative",
          "gestor",
          "supervisor",
          "technical",
          "advogado",
        ],
      },
    ],
  },
  {
    label: MULTAS_E_DEFESAS_MENU_LABEL,
    icon: Scale,
    roles: ["admin", "advogado", "technical", "gestor", "supervisor"],
    subItems: [
      {
        href: MULTAS_DEFESAS_PATH,
        label: MULTAS_DEFESAS_LIST_LABEL,
        icon: List,
        roles: ["admin", "advogado", "technical", "gestor", "supervisor"],
      },
      {
        href: MULTAS_DEFESAS_NOVA_PATH,
        label: MULTAS_DEFESAS_NOVA_LABEL,
        icon: PlusSquare,
        roles: ["admin", "advogado", "technical", "gestor", "supervisor"],
      },
    ],
  },
  {
    label: VISTORIA_TECNICA_MENU_LABEL,
    icon: SearchCheck,
    roles: [
      "admin",
      "technical",
      "gestor",
      "supervisor",
      "advogado",
    ],
    subItems: [
      {
        href: "/inspections",
        label: "Consultar vistorias",
        icon: List,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        href: "/inspections/new",
        label: "Nova vistoria",
        icon: PlusSquare,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        href: "/inspections/reports",
        label: "Relatórios de Campo",
        icon: FileText,
        roles: [
          "admin",
          "gestor",
          "supervisor",
          "technical",
          "advogado",
        ],
      },
    ],
  },
  {
    label: GESTAO_PROCESSOS_MENU_LABEL,
    icon: FolderKanban,
    roles: GESTAO_PROCESSOS_MENU_ROLES,
    subItems: buildGestaoProcessosNavSubItems(),
  },
  {
    label: IA_MENU_LABEL,
    icon: Sparkles,
    roles: [
      "admin",
      "financial",
      "technical",
      "gestor",
      "supervisor",
      "diretor_fauna",
      "advogado",
    ],
    subItems: buildIaNavSubItems(),
  },
  {
    label: ESTUDOS_TECNICOS_MENU_LABEL,
    icon: BookText,
    roles: [
      "admin",
      "technical",
      "gestor",
      "supervisor",
      "diretor_fauna",
      "advogado",
    ],
    subItems: [
      {
        href: "/studies/educacao-ambiental",
        label: "Programa de Educação Ambiental",
        icon: BookOpenCheck,
        roles: [
          "admin",
          "technical",
          "gestor",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        href: "/studies/acao-emergencial",
        label: "Programa de Ação Emergencial",
        icon: AlertTriangle,
        roles: [
          "admin",
          "technical",
          "gestor",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        href: "/studies/eia-rima",
        label: "EIA/RIMA",
        icon: FileQuestion,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        href: "/studies/cavidades",
        label: "Estudo de Cavidades",
        icon: Mountain,
        roles: [
          "admin",
          "technical",
          "gestor",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        href: "/studies/fauna",
        label: "Estudos de Fauna",
        icon: Bird,
        roles: [
          "admin",
          "technical",
          "gestor",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        href: "/studies/ide-sisemanet",
        label: "IDE-SisemaNet",
        icon: MapPinned,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        label: "Inventário Florestal",
        icon: ListTree,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
        subItems: [
          {
            href: "/studies/inventario",
            label: "Inventário Florestal",
            icon: ListTree,
            roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
          },
          {
            href: "/coleta-campo",
            label: "Coleta de campo",
            icon: Smartphone,
            roles: ["admin", "technical", "gestor", "supervisor", "diretor_fauna"],
          },
        ],
      },
      {
        href: "/studies/las-ras",
        label: "LAS-RAS",
        icon: FileSignature,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        href: "/studies/reanalise",
        label: "Reanálise",
        icon: FileSignature,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        href: "/studies/procuracao",
        label: "Procuração",
        icon: FileSignature,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        href: "/studies/mapas",
        label: "Mapas",
        icon: Map,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        href: "/studies/memorial-descritivo",
        label: "Memorial Descritivo",
        icon: FileText,
        roles: [
          "admin",
          "technical",
          "gestor",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
      },
      {
        label: "Outorgas (processos)",
        icon: Droplets,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
        subItems: [
          {
            href: "/studies/outorgas",
            label: "Processos",
            icon: ClipboardList,
            roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
          },
          {
            href: "/studies/outorgas/new",
            label: "Nova outorga",
            icon: PlusSquare,
            roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
          },
        ],
      },
      {
        label: PCA_MENU_LABEL,
        icon: BookMarked,
        roles: PCA_NAV_ROLES,
        subItems: buildPcaNavSubItems(),
      },
      {
        href: "/studies/pia",
        label: "PIA",
        icon: FileCheck,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        href: "/studies/prada",
        label: "PRADA",
        icon: Leaf,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        label: "Projetos e Segurança de Barragens",
        icon: Building2,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
        subItems: [
          {
            href: "/studies/barragens",
            label: "Visão geral",
            icon: LayoutGrid,
            roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
          },
          {
            href: "/studies/barragem",
            label: "Projeto técnico",
            icon: FileText,
            roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
          },
          {
            href: "/studies/seguranca-barragens",
            label: "Segurança e emergência",
            icon: Shield,
            roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
          },
          {
            href: "/studies/piscinao-off-stream",
            label: "Piscinão (off-stream)",
            icon: Waves,
            roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
          },
        ],
      },
      {
        href: "/studies/ptrf",
        label: "PTRF",
        icon: Trees,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        label: RCA_MENU_LABEL,
        icon: NotebookText,
        roles: RCA_NAV_ROLES,
        subItems: buildRcaNavSubItems(),
      },
      {
        label: "Relatórios Diversos",
        icon: FileArchive,
        roles: [
          "admin",
          "technical",
          "gestor",
          "supervisor",
          "diretor_fauna",
          "advogado",
        ],
        subItems: [
          {
            href: "/studies/relatorios-diversos",
            label: "Visão geral",
            icon: FileArchive,
            roles: [
              "admin",
              "technical",
              "gestor",
              "supervisor",
              "diretor_fauna",
              "advogado",
            ],
          },
          {
            href: "/studies/relatorios-diversos/carvao-vegetal",
            label: "Carvão vegetal",
            icon: FileText,
            roles: [
              "admin",
              "technical",
              "gestor",
              "supervisor",
              "diretor_fauna",
              "advogado",
            ],
          },
          {
            href: "/studies/relatorios-diversos/ptrf-prad",
            label: "PTRF / PRAD",
            icon: Trees,
            roles: [
              "admin",
              "technical",
              "gestor",
              "supervisor",
              "diretor_fauna",
              "advogado",
            ],
          },
          {
            href: "/studies/relatorios-diversos/transporte-residuos",
            label: "Transporte de resíduos",
            icon: Truck,
            roles: [
              "admin",
              "technical",
              "gestor",
              "supervisor",
              "diretor_fauna",
              "advogado",
            ],
          },
        ],
      },
      {
        href: "/studies/mtr",
        label: "MTR-MG (resíduos)",
        icon: Recycle,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
      {
        label: "Compensação Ambiental",
        icon: Scale,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
        subItems: [
          {
            href: "/studies/compensacao-ambiental",
            label: "Visão geral",
            icon: Scale,
            roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
          },
          {
            href: "/studies/compensacao-ambiental/especies",
            label: "Espécies protegidas",
            icon: Trees,
            roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
          },
          {
            href: "/studies/compensacao-ambiental/snuc",
            label: "SNUC",
            icon: Scale,
            roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
          },
          {
            href: "/studies/compensacao-ambiental/mata-atlantica",
            label: "Mata Atlântica",
            icon: Leaf,
            roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
          },
          {
            href: "/studies/compensacao-ambiental/mineraria",
            label: "Minerária",
            icon: Building2,
            roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
          },
          {
            href: "/studies/compensacao-ambiental/app",
            label: "Intervenção em APP",
            icon: Droplets,
            roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
          },
        ],
      },
      {
        href: "/studies/reserva-legal",
        label: "Reserva Legal",
        icon: ShieldCheck,
        roles: ["admin", "technical", "gestor", "supervisor", "advogado"],
      },
    ],
  },
  {
    label: GEOREF_MENU_LABEL,
    icon: Crosshair,
    roles: GEOREF_NAV_ROLES,
    subItems: buildGeorefNavSubItems(),
  },
  {
    label: CRM_MENU_LABEL,
    icon: ShoppingCart,
    roles: CRM_NAV_ROLES,
    subItems: buildCrmNavSubItems(),
  },
  {
    href: "/external?url=https%3A%2F%2Fconsultoriapimenta.com.br%3A2096%2F&title=Webmail",
    label: "Webmail",
    icon: Send,
    roles: [
      "admin",
      "technical",
      "sales",
      "financial",
      "gestor",
      "supervisor",
      "diretor_fauna",
      "advogado",
    ],
  },
  {
    href: "/oficios",
    label: OFICIOS_MENU_LABEL,
    icon: Send,
    roles: [
      "admin",
      "client",
      "cliente_autonomo",
      "technical",
      "sales",
      "financial",
      "gestor",
      "supervisor",
      "diretor_fauna",
      "advogado",
    ],
  },
  {
    label: GOV_ACCESS_MENU_LABEL,
    icon: LinkIcon,
    roles: [
      "admin",
      "technical",
      "gestor",
      "financial",
      "sales",
      "supervisor",
      "diretor_fauna",
      "advogado",
    ],
    subItems: buildGovAccessNavSubItems(),
  },
  {
    label: "Ferramentas do Sistema",
    icon: Settings,
    roles: [
      "admin",
      "client",
      "cliente_autonomo",
      "representative",
      "technical",
      "sales",
      "financial",
      "gestor",
      "supervisor",
      "diretor_fauna",
      "advogado",
    ],
    subItems: [
      {
        label: "Empresa e Aparência",
        icon: Building,
        subItems: [
          {
            href: "/settings/company",
            label: "Informações da Empresa",
            icon: Building,
            roles: ["admin"],
          },
          {
            href: "/technical-responsible",
            label: "Responsáveis Técnicos",
            icon: HardHat,
            roles: ["admin", "supervisor", "gestor"],
          },
          {
            href: "/settings#identidade-visual",
            label: "Identidade Visual",
            icon: Palette,
            roles: ["admin"],
          },
          {
            href: "/settings/appearance",
            label: "Aparência",
            icon: Palette,
            roles: [
              "admin",
              "client",
              "cliente_autonomo",
              "representative",
              "technical",
              "sales",
              "financial",
              "gestor",
              "supervisor",
              "diretor_fauna",
              "advogado",
            ],
          },
        ],
      },
      {
        label: "Documentos e Modelos",
        icon: FileText,
        subItems: [
          {
            href: "/settings/templates",
            label: "Templates",
            icon: FileText,
            roles: ["admin"],
          },
          {
            href: "/laudos",
            label: "Laudos",
            icon: BookOpenCheck,
            roles: ["admin", "technical", "gestor", "supervisor"],
          },
          {
            href: "/consultas",
            label: "Consultas Técnicas",
            icon: FileQuestion,
            roles: ["admin", "technical", "gestor", "supervisor", "financial"],
          },
        ],
      },
      {
        label: "IA, RAG e Integrações",
        icon: Bot,
        subItems: [
          {
            href: "/configuracoes/mcp-rag",
            label: "MCP + RAG / Inteligência do Sistema",
            icon: DatabaseZap,
            roles: ["admin"],
          },
          {
            href: "/knowledge-sources",
            label: "Fontes de Conhecimento (RAG)",
            icon: BookMarked,
            roles: ["admin"],
          },
          {
            href: "/ai-lab/cloud-library",
            label: "Biblioteca IA (OneDrive)",
            icon: Folder,
            roles: ["admin"],
          },
          {
            href: "/settings/onedrive-integration",
            label: "Integração OneDrive",
            icon: LinkIcon,
            roles: ["admin"],
          },
          {
            href: "/ai-lab/mcp",
            label: "Ferramentas MCP (lab)",
            icon: Workflow,
            roles: ["admin"],
          },
          {
            href: "/ai-lab/rag",
            label: "Laboratório RAG",
            icon: BookMarked,
            roles: ["admin"],
          },
          {
            href: "/settings/ai-local-source",
            label: "Importação IA (legado local)",
            icon: DatabaseZap,
            roles: ["admin"],
          },
        ],
      },
      {
        label: "Administração e Auditoria",
        icon: ShieldCheck,
        subItems: [
          {
            href: "/settings/deleted-backups",
            label: "Backup de Dados Apagados",
            icon: History,
            roles: ["admin", "supervisor"],
          },
          {
            href: "/settings/files",
            label: "Explorador de Arquivos",
            icon: Folder,
            roles: ["admin"],
          },
          {
            href: "/audit-log",
            label: "Log de Auditoria",
            icon: History,
            roles: ["admin", "supervisor"],
          },
          {
            href: "/canais",
            label: "Canais (WhatsApp/IG)",
            icon: MessagesSquare,
            roles: ["admin"],
          },
        ],
      },
    ],
  },
  {
    href: "/calendar",
    label: "Agenda",
    icon: Calendar,
    roles: [
      "admin",
      "technical",
      "financial",
      "gestor",
      "client",
      "cliente_autonomo",
      "representative",
      "supervisor",
      "sales",
      "diretor_fauna",
      "advogado",
    ],
  },
];
