import React from 'react';
import { cn } from '../../utils/cn';
import type { ToasterProps, ToastOptions, ToastType } from './propTypes.toaster';
type ToastRecord = Required<Pick<ToastOptions, 'id' | 'type'>> & Omit<ToastOptions, 'id' | 'type'> & { message: React.ReactNode };
const listeners = new Set<() => void>();
let toasts: ToastRecord[] = [];
function notify() { listeners.forEach(listener => listener()); }
function add(message: React.ReactNode, options: ToastOptions = {}) { const id = options.id ?? crypto.randomUUID?.() ?? `${Date.now()}-${Math.random()}`; const record: ToastRecord = { id, type: options.type ?? 'default', message, title: options.title, duration: options.duration ?? 4000 }; toasts = [record, ...toasts]; notify(); if (record.duration !== Infinity) window.setTimeout(() => toast.dismiss(id), record.duration); return { id, dismiss: () => toast.dismiss(id), update: (next: Partial<ToastRecord>) => { toasts = toasts.map(item => item.id === id ? { ...item, ...next } : item); notify(); } }; }
export const toast = { show: add, success: (message: React.ReactNode, options?: ToastOptions) => add(message, { ...options, type: 'success' }), error: (message: React.ReactNode, options?: ToastOptions) => add(message, { ...options, type: 'error' }), warning: (message: React.ReactNode, options?: ToastOptions) => add(message, { ...options, type: 'warning' }), info: (message: React.ReactNode, options?: ToastOptions) => add(message, { ...options, type: 'info' }), dismiss: (id: string) => { toasts = toasts.filter(item => item.id !== id); notify(); }, clear: () => { toasts = []; notify(); } };
const tone: Record<ToastType, string> = { success: 'border-green-200 bg-green-50 text-green-900', error: 'border-red-200 bg-red-50 text-red-900', warning: 'border-yellow-200 bg-yellow-50 text-yellow-900', info: 'border-blue-200 bg-blue-50 text-blue-900', default: 'border-gray-200 bg-white text-gray-900' };
export function Toaster({ position = 'top-right', className, ...props }: ToasterProps) { const [, force] = React.useReducer((x) => x + 1, 0); React.useEffect(() => { listeners.add(force); return () => { listeners.delete(force); }; }, []); const pos = position.includes('top') ? 'top-4' : 'bottom-4'; const horiz = position.includes('right') ? 'right-4' : position.includes('left') ? 'left-4' : 'left-1/2 -translate-x-1/2'; return <div aria-live="polite" className={cn('fixed z-[100] grid w-96 max-w-[calc(100vw-2rem)] gap-2', pos, horiz, className)} {...props}>{toasts.map(item => <div key={item.id} className={cn('rounded-lg border p-4 shadow-lg', tone[item.type])}><div className="flex items-start justify-between gap-3"><div>{item.title && <div className="mb-1 font-semibold">{item.title}</div>}<div className="text-sm">{item.message}</div></div><button type="button" aria-label="Fechar" onClick={() => toast.dismiss(item.id)} className="rounded px-1 opacity-70 hover:opacity-100">×</button></div></div>)}</div>; }
